### PR TITLE
Support relative paths in AdditionalIncludeDirectories

### PR DESCRIPTION
**Pull request by Batodalaev**
My repository:

```
Root
--SolutionDir
----solution.sln
----Project1Dir
------Project1.vcxproj
--CodeDir
----Project1Dir
------stdafx.h
------stdafx.cpp
------SomeFolder
--------class.h
--------class.cpp
```

from class.cpp cannot find stdafx.h or other project dirs.

### CODE REVIEW

**Comment by Batodalaev** [comment]
AdditionalIncludeDirectories:

../../CodeDir/Project1Dir
../../CodeDir/Project2Dir

**Comment by Agrael1** [comment]
Did you test it with absolute directories as well?

**Comment by Agrael1** [comment]
Functionality was added for include directories within IncludeDirectories Method

**Comment by Batodalaev** [comment]
> Did you test it with absolute directories as well?

yes, by Path.Combine()

**Pull request closed without merging**
